### ISSUE TITLE
JUnit 5 with Mockto

### ISSUE THREAD

**Issue by phhoef** [phhoef/osgi-test#2]
@timothyjward Hallo Tim, may I ask you for help, again?
I tried to implement a unit test with Junit 5 and Mockito.

For some reason the method annotated with @BeforeEach is not called (even all before or after annotations are ignored).
Do you have a clue why this is happening? The @Test method is executed, but of course some NullPointerExceptions are occurring.

I've extended this little example project with a [Test class](https://github.com/phhoef/osgi-test/blob/master/rest-service/src/test/java/com/my/app/rest/UnitTest.java) for the rest-service
16d62d465787deb19500b9b521c8dc2b9ae237b7

It would be great, if you guide point me in the right directions.
Thanks.

**Comment by timothyjward** [comment]
Bnd has no support for JUnit 5. See bndtools/bnd#2168

You should be fine if you use JUnit 4.

**Comment by phhoef** [comment]
Thanks for your very quick answer. I started with Junit4 (as it is included in the bnd-test bundle, right?).
But unfortunately @Before is also not working.
96290e3b236ffca007c302ae0775d9bf3333832d

**Comment by phhoef** [comment]
Hallo @timothyjward,

I did some tests and it seems that the annotations are completely ignored.
Even if I remove `@Test` or add `@Ignore` the test method will be executed.

The method is named `testSomething`. Only when I change the name of the method to `something` (remove the "test"), then the method will not be executed.

Renaming the `@Before` method to `setUp` or `before` does not change the behavior.

Is there something wrong with my code?

**Comment by timothyjward** [comment]
I have tried checking out 96290e3b236ffca007c302ae0775d9bf3333832d and the unit tests for the rest-service are running fine. Specifically I looked at test `/rest-service/src/test/java/com/my/app/rest/UnitTest.java`

> I did some tests and it seems that the annotations are completely ignored.
Even if I remove @Test or add @Ignore the test method will be executed.

I added `@Ignore` to the test and it was ignored.

> The method is named testSomething. Only when I change the name of the method to something (remove the "test"), then the method will not be executed.
> 
> Renaming the @Before method to setUp or before does not change the behavior.

This is JUnit 3 behaviour, which you will get if you extend `TestCase`. At that point there are no annotations processed because JUnit 3 predates annotations.

> Is there something wrong with my code?

Not in the code that's currently checked in here

> Can you explain how the tests are invoked?
I would have expected the maven-surefire plugin, but I can't see the plugin in any of the dependencies nor in the parent pom. Is there another mechanism for bndtools?

When you use maven to run the unit tests then they are executed by surefire. When you use Eclipse they use the Eclipse JUnit support. Bndtools does not do anything special here. 

The type of testing where bnd/Bndtools does do extra work is in a "Bundle integration test" which would use the `bnd-testing-maven-plugin`. These tests run inside an OSGi framework and have a `bndrun` file which defines the set of bundles to run. To run them in Bndtools you "Run as..." -> "OSGi JUnit Test" by right clicking on the `bndrun` file. You can use the testing archetype from enRoute to create this sort of test.

**Comment by phhoef** [comment]
Hallo @timothyjward,

thanks for testing, even if the result is confusing me.
I think I might trigger the test run in the wrong way.

I am using IntelliJ as IDE.
Basically, I created a run configuration, that executes the `mvn clean test` command.
As I said, the test method is invoked, but others not.
Based on your description, I assume that you're using Eclipse, right?

Do I need a bundle based on the testing archetype from enRoute?

**Comment by timothyjward** [comment]
> Based on your description, I assume that you're using Eclipse, right?

I am, and everything works as expected. I'm surprised that IntelliJ isn't also working as there is no OSGi stuff involved, it's just vanilla Maven.

> Do I need a bundle based on the testing archetype from enRoute?

If you want to write a bundle integration test then yes, you will need one of these to provide the test. If you don't want to write a bundle integration test (they're not compulsory) then you don't need one.

**Comment by phhoef** [comment]
@timothyjward , that's strange.
Running in `mvn clean test` from CMD results in the same.

I am usinging exactly the code which I checked in to the project.
I just added a `System.out.println` statement in the before method to demonstrate, that the method is not being invoked.

`
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.my.app.rest.UnitTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE!
com.my.app.rest.UnitTest.testSomething()  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.NullPointerException
        at com.my.app.rest.UnitTest.testSomething(UnitTest.java:39)


Results :

Failed tests:   com.my.app.rest.UnitTest.testSomething()

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] osgi-test 1.0-SNAPSHOT ............................. SUCCESS [  0.105 s]
[INFO] api ................................................ SUCCESS [  1.419 s]
[INFO] rest-service ....................................... FAILURE [  1.181 s]
[INFO] cmis-repository .................................... SKIPPED
[INFO] chemistry-wrapper .................................. SKIPPED
[INFO] my-app 1.0-SNAPSHOT ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.865 s
[INFO] Finished at: 2018-06-11T16:15:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rest-service: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\phoef\Documents\Projekte\pernexas\osgi-test\rest-service\target\surefire-reports for the individual test results.`

Do you have any ideas, what could be the issue?
I am developing on a Windows 10 machine.

**Comment by timothyjward** [comment]
So this appears to be a problem with the Surefire plugin, which is detecting that your test is a JUnit 3 test. If I put JUnit 4 as a dependency in the project then it works, otherwise it fails, with these telltale lines:

    provider classpath classpath:
    [DEBUG]   /Users/timothyjward/.m2/repository/org/apache/maven/surefire/surefire-junit3/2.12.4/surefire-junit3-2.12.4.jar
    [DEBUG]   /Users/timothyjward/.m2/repository/org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar

I have no clue why this is happening for you. The tests in the enroute examples are written in the same way and work fine...

**Comment by phhoef** [comment]
@timothyjward, thank you so much.
I've added JUnit 4.12 explicitly as dependency and now the `@Before` method is invoked.

Thanks for helping me out, again :-)
